catalogue/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^produit/', include('produits.urls')),
    url(r'^myapp/', include('myapp.urls')),
] + static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.conf.urls import url

from . import views

app_name = 'myapp'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^handel-form/$', views.handel_form, name='handel_form'),
]

produits/urls.py
from django.conf.urls import url

from . import views

app_name = 'produits'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

myapp/models.py
from __future__ import unicode_literals
from django.template.defaultfilters import slugify
from django.db import models

# Create your models here.
class Postable(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    class Meta:
        abstract = True

class Post(Postable):
    """docstring for Produit"""
    title = models.CharField(max_length = 255)
    slug = models.CharField(blank=True, null=True, max_length = 255)
    description = models.TextField(blank=True, null=True)
    prix = models.FloatField(blank=True, null=True)
    poids = models.FloatField(blank=True, null=True)
    visible = models.BooleanField(default=True)

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ('title',)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super(Post, self).save(*args, **kwargs)

produits/models.py
from __future__ import unicode_literals
from django.template.defaultfilters import slugify
from django.db import models
from django.conf import settings

# Create your models here.
class Produit(models.Model):
    """docstring for Produit"""
    title = models.CharField(max_length = 255)
    description = models.TextField()
    prix = models.FloatField()
    poids = models.FloatField()
    tags = models.ManyToManyField('Tag')
    categories = models.ManyToManyField('Categorie')
    visible = models.BooleanField(default=True)

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ('title',)

    def get_feature_image(self):
        return Image.objects.filter(post=self)[:1].get()

class Tag(models.Model):
    """docstring for Tags"""
    tag = models.CharField(max_length = 255)
    def __unicode__(self):
        return self.tag

class Categorie(models.Model):
    """docstring for Categories"""
    categorie = models.CharField(max_length = 255)
    def __unicode__(self):
        return "%s" % (self.categorie)
    class Meta:
        ordering = ('categorie',)

def get_image_filename(instance, filename):
    title = instance.post.title
    slug = slugify(title)
    return "%s-%s" % (slug, filename) 

class Image(models.Model):
    post = models.ForeignKey(Produit, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=settings.BASE_DIR+settings.STATIC_URL+"produits/static/uploads/%Y/%m/%d/",
                              verbose_name='Image')
    def __unicode__(self):
        return "Image du produit : %s" % (self.post.title)

myapp/forms.py
from django import forms
import datetime

class PostForm(forms.Form):
    title = forms.CharField(label='Title', max_length = 255, required=True)
    description = forms.CharField(widget=forms.Textarea , required=True)
    prix = forms.FloatField(label='Prix', required=True)
    poids = forms.FloatField(label='Poids', required=True)
    visible = forms.BooleanField(label='Visible', required=True)
    created = forms.DateField(initial=datetime.date.today)
    updated = forms.DateField(initial=datetime.date.today)

myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

from .forms import PostForm
from .models import Post

# Create your views here.
def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

def handel_form(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = PostForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            obj = Post()
            obj.title = request.POST['title']
            obj.description = request.POST['description']
            obj.prix = request.POST['prix']
            obj.save()
            return HttpResponse("Formulaire Valide.")

    # if a GET (or any other method) we'll create a blank form
    else:
        form = PostForm()

    return render(request, 'form.html', {'form': form})

produits/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
#from django.http import Http404

from .models import Produit, Tag, Categorie

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'produit/index.html'
    context_object_name = 'latest_produits_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Produit.objects.all().order_by('-title')[:5]

class DetailView(generic.DetailView):
    model = Produit
    template_name = 'produit/detail.html'
    context_object_name = 'product'

myapp/templates/form.html
<style type="text/css">
	.mylabel {
		display: block;
		float: left;
		width: 300px
	}
</style>
<form action="" method="post">
    {% csrf_token %}
    {% if form %}
    <!-- Form Errors -->
    {% if form.errors %}
        <ul class="errors">
            {% for error in form.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <!-- Display Form -->
    {% csrf_token %}
    {% for field in form %}
        <div class="mydiv">
            <label class="mylabel">{{ field.label }}</label>
            {{ field }}
        </div>
    {% endfor %}
{% endif %}
    <input type="submit" value="Submit" />
</form>

produits/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/jumbotron-narrow.css' %}" rel="stylesheet">

    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation" class="active"><a href="#">Home</a></li>
            <li role="presentation"><a href="#">About</a></li>
            <li role="presentation"><a href="#">Contact</a></li>
          </ul>
        </nav>
        <h3 class="text-muted">Project name</h3>
      </div>

      <div class="jumbotron">
        <div class="row">
	        <div class="col-md-3">Filtre : </div>
	        <div class="col-md-3">Tri par : </div>
	        <div class="col-md-6">
	        	<a class="btn btn-lg btn-success" href="#" role="button">OK</a>
	        	<input type="text" name="search" placeholder="Recherche ..." id="search" />
	        </div>	        
	    </div>
        
      </div>

      <div class="row marketing">
        {% block content %}{% endblock %}
      </div>

      <footer class="footer">
        <p>© 2015 Company, Inc.</p>
      </footer>

    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
  

</body>
</html>

produits/templates/produit/detail.html
{% extends "base.html" %}
{% block content %}
	{% if product %}
	    <h1>{{ product.title }}</h1>
	    <div class="col-lg-12">
		    <div class="col-lg-8">
		    </div>
		    <div class="col-lg-4">
		    	<p>{{ product.description }}</p>
		    	<h4>Prix : {{ product.prix }} €</h4>
		    	<h4>Poids : {{ product.poids }} kg</h4>
		    	<br/>
		    	<h4>Catégories Attachées :</h4>
		    	<ul style="padding: 0px 10px 0">
		    		{% for cat in product.categories.all %}
		    		<li>{{ cat }}</li>
		    		{% endfor %}
		    	<ul>
		    </div>
	    </div>
	{% else %}
	    <p>Impossible de trouver le produit demandé</p>
	{% endif %}
{% endblock %}

produits/templates/produit/index.html
{% extends "base.html" %}
{% block content %}
	{% if latest_produits_list %}
	    {% for produit in latest_produits_list %}
	        <div class="col-lg-12">
	          <a class="thumbnail" href="{% url 'produits:detail' produit.id %}">
	            <img class="img-responsive" src="http://placehold.it/100x100" alt="">
	          </a>
	          {% load staticfiles %}
	          {{ produit.get_feature_image.image.path  }}
	  		  <h4 class="title">{{ produit.title }} 
	  		  	<span>{{ produit.prix }} €</span>
	  		  	<span>{{ produit.poids }} kg</span>
	  		  </h4>

	          <p>
	          {% autoescape on %}
	          	{{ produit.description|truncatechars:150 }}
	          {% endautoescape %}
	          </p>
	          {% for tag in produit.tags.all %}
	          	{{ tag.tag }}
	          {% endfor %}
	          <spna class="see">
	          	<a href="{% url 'produits:detail' produit.id %}">En savoir plus</a>
	          </spna>
	        </div>
	    {% endfor %}
	{% else %}
	    <p>Aucun produit trouvé !</p>
	{% endif %}
{% endblock %}